# Generated by Django 5.1.4 on 2025-01-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('catagory', models.IntegerField(choices=[(1, 'Vegetables'), (2, 'Eggs'), (3, 'Dairy Products'), (4, 'Meat'), (5, 'Seafoods'), (6, 'Fats and Oils'), (7, 'Spices and Herbs'), (8, 'Bread, Grains and Rices')])),
                ('unit', models.IntegerField(choices=[(1, 'per 100 g'), (10, 'per 1 kg')])),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
    ]
