# Generated by Django 5.1.4 on 2025-01-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='catagory',
            new_name='category',
        ),
    ]
