# Generated by Django 5.1.4 on 2025-01-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prepcard',
            old_name='owner',
            new_name='created_by',
        ),
    ]
