# Generated by Django 5.1.4 on 2025-01-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealpreps', '0002_rename_prepingredient_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prepcard',
            old_name='prep_duration',
            new_name='duration',
        ),
    ]
