# Generated by Django 5.1.4 on 2025-01-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealpreps', '0003_rename_prep_duration_prepcard_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='IngredientUsed',
        ),
    ]
