# Generated by Django 5.1.4 on 2025-01-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_annual_income_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='occupancy',
            new_name='occupation',
        ),
    ]
