# Generated by Django 5.1.4 on 2025-01-28 03:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_codes', '0002_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootAccount',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)])),
                ('name', models.CharField(max_length=50)),
                ('guideline', models.TextField(blank=True, null=True)),
                ('balance', models.IntegerField(choices=[(1, 'Dr'), (2, 'Cr')])),
            ],
            options={
                'verbose_name': 'RootAccount',
                'verbose_name_plural': 'RootAccounts',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='accountlevel2',
            name='level1',
        ),
        migrations.RemoveField(
            model_name='accountlevel3',
            name='level2',
        ),
        migrations.AlterField(
            model_name='account',
            name='level3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='acc_codes.rootaccount'),
        ),
        migrations.DeleteModel(
            name='AccountLevel1',
        ),
        migrations.DeleteModel(
            name='AccountLevel2',
        ),
        migrations.DeleteModel(
            name='AccountLevel3',
        ),
    ]
