# Generated by Django 5.1.4 on 2025-01-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_codes', '0003_rootaccount_remove_accountlevel2_level1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['root', 'sub_account', 'detailed_account'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='level3',
            new_name='root',
        ),
    ]
