# Generated by Django 5.1.4 on 2025-01-29 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_books', '0002_alter_book_abbr_alter_book_unique_together'),
        ('acc_codes', '0004_alter_account_options_rename_level3_account_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='acc_books.book', verbose_name='accounts'),
            preserve_default=False,
        ),
    ]
