# Generated by Django 5.1.4 on 2025-02-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_codes', '0006_alter_account_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
