# Generated by Django 5.1.4 on 2025-01-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_entry_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['entry_type', 'account', 'amount'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='code',
            new_name='account',
        ),
    ]
