# Generated by Django 5.1.4 on 2025-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_entry_options_rename_code_entry_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explaination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('explaination', models.TextField()),
            ],
        ),
    ]
