name: Docker CI

on:
  workflow_dispatch:  # Trigger this after clone repo

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Allow bash script excecution
        run: |
          chmod +x `ls _script/*.sh`
        # grant excecution for new bash script

      - name: Set up Docker with script
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.OCI_INSTANCE_IP }} 'bash -s' < ./_script/build.sh

      
      - name: Recreate .env file from Base64
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.OCI_INSTANCE_IP }} << 'EOF'
          printf "%s" "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > .env
          EOF

      - name: Build Docker image and test DB
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.OCI_INSTANCE_IP }} << 'EOF'
          docker-compose up -d --build
          docker-compose exec web python manage.py check
          EOF